title: Classifier
type: object
description: Processing config body for Classifier filter.
properties:
  enabled:
    type: boolean
  filterSettings:
    type: object
    properties:
      minProbabiliy:
        type: number
      bandwidth:
        type: number
additionalProperties:
  type: object
  properties:
    filterSettings:
      type: object
      properties:
        minProbabiliy:
          type: number
        bandwidth:
          type: number
required:
  - filterSettings
