title: Number of genes vs UMIs
type: object
properties:
  enabled:
    type: boolean
  filterSettings:
    type: object
    properties:
      regressionType:
        type: string
        minLength: 1
      smoothing:
        type: number
      upperCutoff:
        type: number
      lowerCutoff:
        type: number
      stringency:
        type: number
      binStep:
        type: number
required:
  - filterSettings
description: Processing config body for Number of genes vs UMIs filter.
