title: Cell Size Distribution
type: object
properties:
  enabled:
    type: boolean
  filterSettings:
    type: object
    properties:
      minCellSize:
        type: number
      binStep:
        type: number
required:
  - filterSettings
description: Processing config body for Cell Size Distribution filter.
