title: Dimensionality Reduction
type: object
properties:
  method:
    type: string
    minLength: 1
  methodSettings:
    type: object
    properties:
      pca:
        type: object
        properties:
          maxPCs:
            type: number
  interpolate:
    type: string
    minLength: 1
  excludeGeneCategories:
    type: object
    properties:
      ribosomal:
        type: boolean
      mitochondrial:
        type: boolean
      cellCycle:
        type: boolean
required:
  - method
  - methodSettings
  - interpolate
  - excludeGeneCategories
description: Processing config body for Dimensionality Reduction filter.
