title: Plots & Tables configuration
type: object
description: A file specifying the configuration for a given plot/table.
properties:
  experimentId:
    type: string
    description: The ID of the experiment.
  plotUuid:
    type: string
    description: The UUID of the plot or table.
  plotType:
    type: string
    description: The type of the plot to be saved. Can be one of the values specified herein.
    enum:
      - umisInCells
      - umisCellRank
      - mitochondrialContent
      - mitochondrialReads
      - classifierContour
      - genesVsUmisHistogram
      - genesVsUmisScatterplot
      - doubletScoreHistogram
      - dataIntegrationEmbedding
      - dataIntegrationFrequency
      - dataIntegrationElbow
      - embeddingCategorical
      - embeddingContinuous
      - embeddingPreviewBySample
      - embeddingPreviewByCellSets
      - embeddingPreviewMitochondrialContent
      - embeddingPreviewDoubletScore
      - volcano
      - heatmap
      - frequency
  config:
    type: object
required:
  - plotType
  - config
